# -*- coding: utf-8 -*-
"""КП6_DA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fKFQTQG_lTKB1qrGggVNoP78_oVQ_Q6k
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
import numpy as np
import plotly.express as px
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('streamlit_dataset.csv')
df["ConversionRate"] = (df["ConversionRate"] * 100).round(2)
df["ROI"] = (df["ROI"] * 100).round(2)
df["RevenuePerCustomer"] = (df["RevenuePerCustomer"] * 100).round(2)

st.set_page_config(
    page_title="Companies Dashboard",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={
        'Get Help': 'https://docs.streamlit.io/',
        'Report a bug': 'https://github.com/streamlit/streamlit/issues',
        'About': 'Interactive Dashboard For Business Analysis'
    }
)

st.sidebar.title("Filter Panel")

selected_year = st.sidebar.selectbox("Year", sorted(df["Year"].unique()))
selected_region = st.sidebar.multiselect("Region", df["Region"].unique(), default=df["Region"].unique())
selected_industry = st.sidebar.multiselect("Industry", df["Industry"].unique(), default=df["Industry"].unique())
selected_scenario = st.sidebar.radio("Scenario", df["Scenario"].unique())

selected_max_adbudget = st.sidebar.slider(
    "Max Ad Budget",
    min_value=int(df["AdBudget"].min()),
    max_value=int(df["AdBudget"].max()),
    value=int(df["AdBudget"].max()),
    step=1000
)

df_filtered = df[
    (df["Year"] == selected_year) &
    (df["Region"].isin(selected_region)) &
    (df["Industry"].isin(selected_industry)) &
    (df["Scenario"] == selected_scenario) &
    (df["AdBudget"] <= selected_max_adbudget)
]

show_map = st.sidebar.checkbox("Show the map with filtered companies")

chart_option = st.sidebar.radio(
    "Select a chart:",
    [
        "Revenue per customer vs. Expenses",
        "Boxplot of Profits by Industry",
        "Scatter: Profit vs. Investment",
        "Conversion Histogram by Industry",
        "Funnel by Industry",
        "Linear Regression"
    ]
)

st.sidebar.markdown("## Clustering")
numeric_columns = df_filtered.select_dtypes(include=np.number).columns.tolist()
cluster_features = st.sidebar.multiselect(
    "Select numerical variables for clustering",
    numeric_columns,
    default=["ROI", "Investment"]
)
k = st.sidebar.slider("Clusters (K)", 2, 6, 3)
normalize = st.sidebar.checkbox("Normalize the data before clustering", value=False)
show_clustering = st.sidebar.checkbox("Show clustering", value=False)

regression_options = {
    "Revenue vs Investment": ("Investment", "Revenue"),
    "Profit vs Expenses": ("Expenses", "Profit"),
    "Revenue vs Customers": ("Customers", "Revenue"),
    "ROI vs AdBudget": ("AdBudget", "ROI")
}
st.sidebar.markdown("## Regression Model")
selected_model = st.sidebar.selectbox(
    "Select a regression model",
    list(regression_options.keys())
)
reg_x, reg_y = regression_options[selected_model]
show_regression = st.sidebar.checkbox("Show regression", value=False)

st.sidebar.markdown("Clustering Analysis")
numeric_columns = df_filtered.select_dtypes(include=np.number).columns.tolist()

cl_x = st.sidebar.selectbox("Select variable X", numeric_columns, index=0)
cl_y = st.sidebar.selectbox("Select the Y variable", numeric_columns, index=1)
show_clustering = st.sidebar.checkbox("Show Clustering Analysis")

st.sidebar.markdown("---")
st.sidebar.markdown(" **Author**: yuliia-kravchenko")

st.title("Economic And Financial Companies Dashboard")
st.subheader(f"{df_filtered.shape[0]} Companies Filtered")
st.subheader(" **Instructions**: In the sidebar, select the criteria you want to use to filter the data, and view the charts below.")

csv = df_filtered.to_csv(index=False).encode("utf-8")
st.download_button(
    label="⬇ Download CSV",
    data=csv,
    file_name="filtered_companies.csv",
    mime="text/csv"
)

st.subheader("Оберіть, які стовпці таблиці відображати")

all_columns = df_filtered.columns.tolist()
default_columns = ["Company", "Region", "Industry", "Profit", "ROI"]

selected_columns = st.multiselect(
    "Оберіть стовпці для перегляду",
    options=all_columns,
    default=[col for col in default_columns if col in all_columns]
)

if selected_columns:
    st.dataframe(df_filtered[selected_columns])
else:
    st.info("Оберіть хоча б один стовпець, щоб побачити таблицю.")

if show_map:
    st.subheader("🗺 Географія компаній")

    map_data = df_filtered[["Latitude", "Longitude"]].dropna().rename(
        columns={"Latitude": "latitude", "Longitude": "longitude"}
    )

    if not map_data.empty:
        st.map(map_data)
    else:
        st.warning("Немає доступних координат для побудови карти.")

if chart_option == "Revenue per customer vs. Expenses":
    st.subheader("Revenue per customer vs. Expenses")
    chart = px.scatter(
        df,
        x="Expenses",
        y="RevenuePerCustomer",
        color="Industry",
        hover_data=["Company", "Industry"]
    )
    chart.update_layout(title="Revenue per customer vs. Expenses")
    st.plotly_chart(chart, use_container_width=True)

elif chart_option == "Boxplot of Profits by Industry":
    st.subheader("Boxplot of profits by industry")
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.boxplot(data=df_filtered, x="Industry", y="Profit", ax=ax)
    ax.set_title("Profit distribution by industry")
    st.pyplot(fig)

elif chart_option == "Scatter: Profit vs. Investment":
    st.subheader("Scatter: Profit vs. Investment")
    chart = px.scatter(
        df_filtered,
        x="Investment",
        y="Profit",
        color="Industry",
        hover_data=["Company", "Industry"]
    )
    chart.update_layout(title="Scatter: Profit vs. Investment")
    st.plotly_chart(chart, use_container_width=True)

elif chart_option == "Conversion Histogram by Industry":
    st.subheader("Bar chart: Average conversion rate by industry")
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.barplot(data=df_filtered, x="Industry", y="ConversionRate", estimator="mean", ax=ax)
    ax.set_title("Average Conversion Rate by Industry")
    st.pyplot(fig)

elif chart_option == "Funnel by Industry":
    st.subheader("Revenue funnel → profit")

    funnel_data = {
        "Stage": ["Ad Budget", "Customers", "Revenue", "Profit"],
        "Value": [
            df["AdBudget"].sum(),
            df["Customers"].sum(),
            df["Revenue"].sum(),
            df["Profit"].sum()
        ]
    }
    funnel_df = pd.DataFrame(funnel_data)

    fig = px.funnel(
        funnel_df,
        x="Value",
        y="Stage",
        title="The Business Funnel: From Costs to Profits"
    )
    fig.update_layout(title="Bar chart: Average conversion rate by industry")
    st.plotly_chart(fig, use_container_width=True)

if show_clustering:
    st.subheader("Clustering of companies")
    if len(cluster_features) >= 2:
        cluster_data = df[cluster_features].dropna().copy()
        if cluster_data.shape[0] >= k:

            if normalize:
                scaler = StandardScaler()
                cluster_data[cluster_features] = scaler.fit_transform(cluster_data)

            kmeans = KMeans(n_clusters=k, random_state=0)
            cluster_data["Cluster"] = kmeans.fit_predict(cluster_data)

            fig = px.scatter(
                cluster_data,
                x=cluster_features[0],
                y=cluster_features[1],
                color="Cluster",
                title="Clustering"
            )
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.warning("There is not enough data for clustering (rows < K).")
    else:
        st.info("Select at least 2 variables for clustering.")

if show_regression:
    st.subheader(f"Linear Regression: {reg_y} ~ {reg_x}")
    df_reg = df_filtered[[reg_x, reg_y]].dropna()
    if df_reg.shape[0] >= 2:
        model = LinearRegression()
        model.fit(df_reg[[reg_x]], df_reg[reg_y])
        y_pred = model.predict(df_reg[[reg_x]])
        coef = model.coef_[0]
        intercept = model.intercept_
        r2 = model.score(df_reg[[reg_x]], df_reg[reg_y])

        st.markdown(f"**Slope coefficient (β):** {coef:.4f}")
        st.markdown(f"Intersept:** {intercept:.4f}")
        st.markdown(f"**R²:** {r2:.4f}")

        fig, ax = plt.subplots(figsize=(8, 5))
        sns.scatterplot(data=df_reg, x=reg_x, y=reg_y, ax=ax)
        sns.lineplot(x=df_reg[reg_x], y=y_pred, color='red', ax=ax)
        ax.set_title(f"Regression {reg_y} ~ {reg_x}")
        st.pyplot(fig)
    else:
        st.warning("There is not enough data to perform a regression.")